name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, gd, intl, mbstring, openssl, pdo, pdo_mysql, tokenizer, zip
          coverage: xdebug #optional

      - name: Set environment
        run: |
          set -e
          sed -i "s|^\(DB_HOST=\s*\).*$|\1127.0.0.1|" .env.testing
          sed -i "s|^\(DB_PORT=\s*\).*$|\1${{ job.services.mysql.ports['3306'] }}|" .env.testing
          printf "the complete .env.testing ...\n\n"
          cat .env.testing
      - name: Composer install
        run: |
          set -e
          composer install --no-interaction --ansi --no-progress --no-suggest --optimize-autoloader
      - name: Migrate database
        run: set -e && php artisan migrate --env=testing
      - name: Test with phpunit
        run: php artisan test --coverage-text --verbose
